services:
  postgres:
    container_name: task-hero-db
    image: postgres:16.1-alpine
    ports: [5432:5432]
    volumes: [./pg/data:/var/lib/postgresql/data, ./pg/init:/docker-entrypoint-initdb.d]
    environment: [POSTGRES_PASSWORD=postgres]
