### Local dev config ###

spring.datasource:
  url: jdbc:postgresql://localhost:5432/taskherodb?reWriteBatchedInserts=true
  username: postgres
  password: postgres
spring.jpa.properties.hibernate:
  highlight_sql: true
#  format_sql: true
#  use_sql_comments: true
#  generate_statistics: true

logging.level:
  org.springframework:
    orm: DEBUG
    transaction: DEBUG
    web: DEBUG
  org.hibernate:
    SQL: DEBUG
#    orm.jdbc.bind: TRACE
#    stat: DEBUG

management.endpoints:
  enabled-by-default: true
  web.exposure.include: '*'
